apiVersion: v1
kind: ServiceAccount
metadata:
  name: unihub-fluent-bit
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unihub-fluent-bit
rules:
- apiGroups:
  - ''
  resources:
  - pods
  - namespaces
  - nodes
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: unihub-fluent-bit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: unihub-fluent-bit
subjects:
- kind: ServiceAccount
  name: unihub-fluent-bit
  namespace: logging
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
spec:
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      serviceAccountName: unihub-fluent-bit
      tolerations:
      - operator: Exists
        effect: NoSchedule
      containers:
      - name: fluent-bit
        image: cr.fluentbit.io/fluent/fluent-bit:3.2.10
        ports:
        - name: http
          containerPort: 2020
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 128Mi
        readinessProbe:
          httpGet:
            path: /api/v1/metrics
            port: http
        volumeMounts:
        - name: logs
          mountPath: /var/log
          readOnly: true
        - name: config
          mountPath: /fluent-bit/etc
          readOnly: true
        - name: buffers
          mountPath: /buffers
      volumes:
      - name: logs
        hostPath:
          path: /var/log
      - name: config
        configMap:
          name: fluent-bit-config
      - name: buffers
        hostPath:
          path: /var/lib/unihub-fluent-bit
          type: DirectoryOrCreate
