-- Virtual Waiting Room Queue Management with Randomized Priority
--
-- KEYS[1] = queue key (Sorted Set: user_id -> priority score)
-- KEYS[2] = active tokens key (Sorted Set: user_id -> expiration timestamp)
-- KEYS[3] = heartbeat key (Sorted Set: user_id -> heartbeat expiration timestamp)
--
-- ARGV[1] = user_id
-- ARGV[2] = now (current timestamp in seconds, float)
-- ARGV[3] = open_time (registration start time in seconds, float)
-- ARGV[4] = max_active (max concurrent users allowed in active set)
-- ARGV[5] = token_ttl (seconds user has to complete registration, e.g. 300)
-- ARGV[6] = heartbeat_ttl (seconds until queued user is considered abandoned, e.g. 60)
-- ARGV[7] = weight (time penalty multiplier, e.g. 100)
-- ARGV[8] = random_val (random value generated by backend, e.g. 0-3000)
--
-- Returns: {status, position_or_ttl, total_in_queue}
--   status = 1: user granted access (proceed to register)
--   status = 2: user queued (wait in line)
--   status = 3: user already has active token (proceed)
--   status = 0: user already in queue (return current position)

local queue_key = KEYS[1]
local active_key = KEYS[2]
local heartbeat_key = KEYS[3]

local user_id = ARGV[1]
local now = tonumber(ARGV[2])
local open_time = tonumber(ARGV[3])
local max_active = tonumber(ARGV[4])
local token_ttl = tonumber(ARGV[5])
local heartbeat_ttl = tonumber(ARGV[6])
local weight = tonumber(ARGV[7])
local random_val = tonumber(ARGV[8])

-- 1. Purge expired active tokens
redis.call('ZREMRANGEBYSCORE', active_key, 0, now)

-- 2. Purge dead waiting users (heartbeat expired > 60s without request/poll)
local dead_users = redis.call('ZRANGEBYSCORE', heartbeat_key, 0, now)
if #dead_users > 0 then
    for _, uid in ipairs(dead_users) do
        redis.call('ZREM', queue_key, uid)
        redis.call('ZREM', heartbeat_key, uid)
    end
end

-- 3. Check if user already has an active access token
local active_exp = redis.call('ZSCORE', active_key, user_id)
if active_exp and tonumber(active_exp) > now then
    local remaining = math.floor(tonumber(active_exp) - now)
    return {3, remaining, 0} -- Already has active access
end

-- 4. Check if user is already in queue
local existing_score = redis.call('ZSCORE', queue_key, user_id)
if existing_score then
    -- Reset heartbeat expiration (extend heartbeat_ttl seconds from now)
    redis.call('ZADD', heartbeat_key, now + heartbeat_ttl, user_id)
    redis.call('EXPIRE', queue_key, 3600)
    redis.call('EXPIRE', heartbeat_key, 3600)

    local position = redis.call('ZRANK', queue_key, user_id)
    local total = redis.call('ZCARD', queue_key)
    return {0, position + 1, total}
end

-- 5. Count active users and queued users
local active_count = redis.call('ZCARD', active_key)
local queue_count = redis.call('ZCARD', queue_key)

-- If queue is empty and there's room in active set, grant immediate access
if queue_count == 0 and active_count < max_active then
    redis.call('ZADD', active_key, now + token_ttl, user_id)
    redis.call('EXPIRE', active_key, 3600)
    return {1, token_ttl, 0} -- Granted access
end

-- 6. Add user to queue using the user's formula:
-- score = (max(0, now - open_time) * weight) + random_val
local delta_t = math.max(0, now - open_time)
local score = (delta_t * weight) + random_val

redis.call('ZADD', queue_key, score, user_id)
redis.call('ZADD', heartbeat_key, now + heartbeat_ttl, user_id)
redis.call('EXPIRE', queue_key, 3600)
redis.call('EXPIRE', heartbeat_key, 3600)

local position = redis.call('ZRANK', queue_key, user_id)
local total = redis.call('ZCARD', queue_key)

return {2, position + 1, total} -- Queued at position
