apiVersion: v1
kind: Namespace
metadata:
  name: unihub-ci
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: unihub-ci
  namespace: unihub-ci
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: unihub-ci
  namespace: unihub-ci
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflowtaskresults
  verbs:
  - create
  - patch
- apiGroups:
  - ''
  resources:
  - pods
  - pods/log
  - services
  - configmaps
  - secrets
  - persistentvolumeclaims
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  - replicasets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: unihub-ci
  namespace: unihub-ci
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: unihub-ci
subjects:
- kind: ServiceAccount
  name: unihub-ci
  namespace: unihub-ci
