apiVersion: v2
name: unihub
description: Enterprise-grade Helm Chart for UniHub Multi-tier Microservices Platform
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - unihub
  - golang
  - nextjs
  - devops
maintainers:
  - name: Tuan Duy
    email: dtuanduy2005@gmail.com
