global:
  environment: production
api:
  replicaCount: 2
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 8
worker:
  replicaCount: 2
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 20
web:
  replicaCount: 2
media:
  existingClaim: unihub-media
  accessModes:
  - ReadWriteMany
podMonitor:
  enabled: true
config:
  runSeed: 'false'
  webUrl: https://unihub.example.com
  corsOrigins: https://unihub.example.com
ingress:
  enabled: true
  hosts:
  - host: unihub.example.com
    paths:
    - path: /api/v1
      pathType: Prefix
      serviceName: unihub-api-service
      servicePort: 80
    - path: /
      pathType: Prefix
      serviceName: unihub-web-service
      servicePort: 80
  tls:
  - secretName: unihub-prod-tls
    hosts:
    - unihub.example.com
mailpit:
  enabled: false
