apiVersion: v1
kind: Secret
metadata:
  name: unihub-secret
  labels:
    {{- include "unihub.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  AUTH_SECRET: {{ .Values.secrets.authSecret | quote }}
  RSA_PRIVATE_KEY: {{ .Values.secrets.rsaPrivateKey | quote }}
  GEMINI_API_KEY: {{ .Values.secrets.geminiApiKey | quote }}
  SMTP_USER: {{ .Values.secrets.smtpUser | quote }}
  SMTP_PASS: {{ .Values.secrets.smtpPass | quote }}
